import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const apercu = localFont({
  src: [
    {
      path: "./fonts/ApercuLight.otf",
      weight: '100',
      style: 'normal',
    },
    {
      path: "./fonts/ApercuLightItalic.otf",
      weight: '100',
      style: 'italic',
    },
    {
      path: "./fonts/ApercuRegular.otf",
      weight: '400',
      style: 'normal',
    },
    {
      path: "./fonts/ApercuBold.otf",
      weight: '700',
      style: 'normal',
    }
  ],
  variable: '--font-apercu',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${apercu.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
